import React from "react";
import { Plus, Trash2, ChevronDown, ChevronRight } from "lucide-react";
import v4 from "@/lib/uuid";

const TextInput = ({ label, value, onChange, placeholder }) => (
  <label className="block"><span className="label-base">{label}</span><input className="input-base" value={value || ""} onChange={e => onChange(e.target.value)} placeholder={placeholder} /></label>
);
const Section = ({ title, count, children, defaultOpen = true }) => {
  const [open, setOpen] = React.useState(defaultOpen);
  return (<section className="border-b border-[#DCD7CE] pb-6 mb-6"><button type="button" onClick={() => setOpen(v => !v)} className="flex justify-between w-full mb-3"><span className="font-serif-display text-[22px]">{title} {typeof count === "number" && <span className="text-sm text-[#5C5A56]">({count})</span>}</span>{open ? <ChevronDown /> : <ChevronRight />}</button>{open && <div className="space-y-3">{children}</div>}</section>);
};
export default function ResumeForm({ resume, setResume }) {
  const update = (path, value) => setResume(prev => { const next = JSON.parse(JSON.stringify(prev)); const keys = path.split("."); let cur = next; for (let i = 0; i < keys.length-1; i++) cur = cur[keys[i]]; cur[keys[keys.length-1]] = value; return next; });
  const updateList = (key, idx, field, val) => setResume(p => ({ ...p, [key]: p[key].map((item, i) => i === idx ? { ...item, [field]: val } : item) }));
  const addItem = (key, item) => setResume(p => ({ ...p, [key]: [...p[key], item] }));
  const removeItem = (key, idx) => setResume(p => ({ ...p, [key]: p[key].filter((_, i) => i !== idx) }));
  return (
    <form onSubmit={e => e.preventDefault()}>
      <Section title="Personal Details"><div className="grid grid-cols-2 gap-3"><TextInput label="Full name" value={resume.personal.fullName} onChange={v => update("personal.fullName", v)} /><TextInput label="Title" value={resume.personal.title} onChange={v => update("personal.title", v)} /><TextInput label="Email" value={resume.personal.email} onChange={v => update("personal.email", v)} /><TextInput label="Phone" value={resume.personal.phone} onChange={v => update("personal.phone", v)} /><TextInput label="Location" value={resume.personal.location} onChange={v => update("personal.location", v)} /><TextInput label="Website" value={resume.personal.website} onChange={v => update("personal.website", v)} /></div><textarea className="input-base" rows={3} value={resume.personal.summary} onChange={e => update("personal.summary", e.target.value)} placeholder="Summary" /></Section>
      <Section title="Experience" count={resume.experience.length}>{resume.experience.map((e, i) => (<div key={e.id} className="border p-4 rounded relative"><button type="button" onClick={() => removeItem("experience", i)} className="absolute top-2 right-2 text-red-500 hover:text-red-700"><Trash2 size={16} /></button><div className="grid grid-cols-2 gap-3"><TextInput label="Role" value={e.role} onChange={v => updateList("experience", i, "role", v)} /><TextInput label="Company" value={e.company} onChange={v => updateList("experience", i, "company", v)} /><TextInput label="Start" value={e.startDate} onChange={v => updateList("experience", i, "startDate", v)} /><TextInput label="End" value={e.endDate} onChange={v => updateList("experience", i, "endDate", v)} /><TextInput label="Location" value={e.location} onChange={v => updateList("experience", i, "location", v)} /></div><textarea className="input-base mt-2" rows={3} value={(e.bullets || []).join("\n")} onChange={v => updateList("experience", i, "bullets", v.target.value.split("\n"))} placeholder="Bullets (one per line)" /></div>))}<button type="button" onClick={() => addItem("experience", { id: v4(), company: "", role: "", startDate: "", endDate: "", location: "", bullets: [] })} className="flex items-center gap-2 text-[#1E3F33] font-medium"><Plus size={14} /> Add experience</button></Section>
      <Section title="Education" count={resume.education.length} defaultOpen={false}>{resume.education.map((e, i) => (<div key={e.id} className="border p-4 rounded relative"><button type="button" onClick={() => removeItem("education", i)} className="absolute top-2 right-2 text-red-500 hover:text-red-700"><Trash2 size={16} /></button><div className="grid grid-cols-2 gap-3"><TextInput label="School" value={e.school} onChange={v => updateList("education", i, "school", v)} /><TextInput label="Degree" value={e.degree} onChange={v => updateList("education", i, "degree", v)} /><TextInput label="Field" value={e.field} onChange={v => updateList("education", i, "field", v)} /><TextInput label="Start" value={e.startDate} onChange={v => updateList("education", i, "startDate", v)} /><TextInput label="End" value={e.endDate} onChange={v => updateList("education", i, "endDate", v)} /><TextInput label="Location" value={e.location} onChange={v => updateList("education", i, "location", v)} /><TextInput label="Details" value={e.details} onChange={v => updateList("education", i, "details", v)} /></div></div>))}<button type="button" onClick={() => addItem("education", { id: v4(), school: "", degree: "", field: "", startDate: "", endDate: "", location: "", details: "" })} className="flex items-center gap-2 text-[#1E3F33] font-medium"><Plus size={14} /> Add education</button></Section>
      <Section title="Projects" count={resume.projects.length} defaultOpen={false}>{resume.projects.map((p, i) => (<div key={p.id} className="border p-4 rounded relative"><button type="button" onClick={() => removeItem("projects", i)} className="absolute top-2 right-2 text-red-500 hover:text-red-700"><Trash2 size={16} /></button><div className="grid grid-cols-2 gap-3"><TextInput label="Name" value={p.name} onChange={v => updateList("projects", i, "name", v)} /><TextInput label="Link" value={p.link} onChange={v => updateList("projects", i, "link", v)} /><TextInput label="Tech" value={p.tech} onChange={v => updateList("projects", i, "tech", v)} /><TextInput label="Description" value={p.description} onChange={v => updateList("projects", i, "description", v)} /></div><textarea className="input-base mt-2" rows={3} value={(p.bullets || []).join("\n")} onChange={v => updateList("projects", i, "bullets", v.target.value.split("\n"))} placeholder="Bullets (one per line)" /></div>))}<button type="button" onClick={() => addItem("projects", { id: v4(), name: "", link: "", tech: "", description: "", bullets: [] })} className="flex items-center gap-2 text-[#1E3F33] font-medium"><Plus size={14} /> Add project</button></Section>
      <Section title="Skills" count={resume.skills.length} defaultOpen={false}>{resume.skills.map((s, i) => (<div key={s.id} className="border p-4 rounded relative"><button type="button" onClick={() => removeItem("skills", i)} className="absolute top-2 right-2 text-red-500 hover:text-red-700"><Trash2 size={16} /></button><TextInput label="Category" value={s.category} onChange={v => updateList("skills", i, "category", v)} /><textarea className="input-base mt-2" rows={2} value={(s.items || []).join(", ")} onChange={v => updateList("skills", i, "items", v.target.value.split(",").map(x => x.trim()))} placeholder="Items (comma separated)" /></div>))}<button type="button" onClick={() => addItem("skills", { id: v4(), category: "", items: [] })} className="flex items-center gap-2 text-[#1E3F33] font-medium"><Plus size={14} /> Add skill</button></Section>
      <Section title="Certifications" count={resume.certifications.length} defaultOpen={false}>{resume.certifications.map((c, i) => (<div key={c.id} className="border p-4 rounded relative"><button type="button" onClick={() => removeItem("certifications", i)} className="absolute top-2 right-2 text-red-500 hover:text-red-700"><Trash2 size={16} /></button><div className="grid grid-cols-2 gap-3"><TextInput label="Name" value={c.name} onChange={v => updateList("certifications", i, "name", v)} /><TextInput label="Issuer" value={c.issuer} onChange={v => updateList("certifications", i, "issuer", v)} /><TextInput label="Date" value={c.date} onChange={v => updateList("certifications", i, "date", v)} /><TextInput label="Link" value={c.link} onChange={v => updateList("certifications", i, "link", v)} /></div></div>))}<button type="button" onClick={() => addItem("certifications", { id: v4(), name: "", issuer: "", date: "", link: "" })} className="flex items-center gap-2 text-[#1E3F33] font-medium"><Plus size={14} /> Add certification</button></Section>
    </form>
  );
}
